### ISSUE TITLE
task not serializable when used it as a broadcast variable in spark application

### ISSUE THREAD

**Issue by h2coder** [komiya-atsushi/xgboost-predictor-java#11]
Hi, 
      Recently, i used your project in my spark application. A predictor instance is broadcast to all workers,  and then the same problem occurs as in [task-not-serializable-exception](https://forums.databricks.com/questions/369/how-do-i-handle-a-task-not-serializable-exception.html)       
      And i solve the problem as the top answer in the above link, like below and add the 'Serializable' inheritance in all the member family class/interface of Predictor : 

`public class Predictor implements Serializable`
   
   If u have time, can u support the Serializable feature , or i can do some help.

**Comment by komiya-atsushi** [comment]
Hi,

Thank you for using the library and reporting the problem.

I just released [xgboost-predictor-0.1.8](https://bintray.com/komiya-atsushi/maven/xgboost-predictor/0.1.8) which you may be able to use on Spark.

Could you try out a new version?
