### ISSUE TITLE
xgboost4j-spark model is not compatible with c-based model. 

### ISSUE THREAD

**Issue by JC-R** [komiya-atsushi/xgboost-predictor-java#15]
I would like to use this code in spark, as it is pure java based and would fit in nicely into my spark pipeline. xgboost4j relies on c-based shared libraries not available on the nodes, so I cannot deploy to the cluster. Unfortunately, the new scala/spark-generated models are not compatible.

**Comment by komiya-atsushi** [comment]
xgboost-predictor 0.2.0 supports loading model files generated by xgboost4j-spark.
(Constructor of class `Predictor` can handle both c-based and xgboost4j-spark-generated models)

Also I just made [xgboost-predictor-spark](https://github.com/komiya-atsushi/xgboost-predictor-java/tree/master/xgboost-predictor-spark) that provides xgboost-predictor functions as Spark ML API.
If you have any interests in the module, please try to use it 😃

**Comment by JC-R** [comment]
I will try and post my thoughts here. Thanks!!
