### ISSUE TITLE
Support DART booster

### ISSUE THREAD

**Issue by kretes** [komiya-atsushi/xgboost-predictor-java#24]
Hello,

Currently xgboost-predictor-java does not support models trained with DART booster: https://github.com/dmlc/xgboost/blob/40c6e2f0c84db46070f91cf77db03275a1f4eee9/src/gbm/gbtree.cc#L618

There is a whitelist of allowed predictors here: https://github.com/komiya-atsushi/xgboost-predictor-java/blob/78d839d317649b2d1d599b3e931d92842013d570/xgboost-predictor/src/main/java/biz/k11i/xgboost/gbm/GradBooster.java#L20

AFAIU - Dart is a modification of gbtree which just influences the training phase, at inference - it is the same. 
I wonder if a fix of just treating dart as gbtree would work ok - what do You think?

**Comment by jbojar** [comment]
@komiya-atsushi This issue can be closed now as #27 has been merged.
