### ISSUE TITLE
Support newer model file format with backward compatible

### ISSUE THREAD

**Issue by komiya-atsushi** [komiya-atsushi/xgboost-predictor-java#3]
Recent model file format of XGBoost is removed the header string `binf`.
https://github.com/dmlc/xgboost/blob/fc4c88fceb84e9b098f68aec44583b3db0168f8b/src/learner.cc#L214-L220

**Comment by lisendong** [comment]
hi, I'm using your java predictor.
when will you plan to update this issue?
Or could you tell me how to do?

**Comment by komiya-atsushi** [comment]
Thank you for using the predictor.

I'm working on it and I'll release 0.1.7 in a few days.

**Comment by komiya-atsushi** [comment]
xgboost-predictor 0.1.7 released :smiley:
https://bintray.com/komiya-atsushi/maven/xgboost-predictor/0.1.7/view
