### ISSUE TITLE
GBTree.predict with ntree_limit set too high for used model throws ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by jbojar** [komiya-atsushi/xgboost-predictor-java#34]
If `ntree_limit` parameter in `GBTree.predict` method is set too high for used model then it throws `ArrayIndexOutOfBoundsException`.

It would be more convenient if it just evaluated the model with maximum available trees. Especially as it is not possible to obtain max tree limit from `Predictor` instance.

**Comment by komiya-atsushi** [comment]
Thank you for your contribution!
