### ISSUE TITLE
How to create the model using this library?

### ISSUE THREAD

**Issue by alaeddinms** [komiya-atsushi/xgboost-predictor-java#4]
Hi,

 How to create the prediction model? is this library for prediction with a model generated somewhere else?

Thanks,

Alaeddin

**Comment by komiya-atsushi** [comment]
@alaeddinms 

This library only provides functions to *predict*, and *training* functions are never provided.

If you want to build a prediction model, you should use [xgboost](https://github.com/dmlc/xgboost)  via command-line interface or some language bindings like [XGBoost4J](https://github.com/dmlc/xgboost/tree/master/jvm-packages).

**Comment by alaeddinms** [comment]
Thanks
