### ISSUE TITLE
How to treat the missing values?

### ISSUE THREAD

**Issue by xdwangh** [komiya-atsushi/xgboost-predictor-java#6]
I trained model by xgboost with missing value. I don't know how to treat missing value in this tools

**Comment by xdwangh** [comment]
I found that I can set missing value as zero in file "FVec.java". However, some feature values actually are zeros.

**Comment by komiya-atsushi** [comment]
@xdwangh 

You can represent *missing values* using `Float.NaN` or `Double.NaN`.

```java
double[] featureValues = {
        1.0,
        Float.NaN, // missing value
        0.0,
        // ...
};

FVec fv = FVec.Transformer.fromArray(featureValues, false /* = do not treats zero as missing value */);
```
