### ISSUE TITLE
Scala API

### ISSUE THREAD

**Issue by geoHeil** [komiya-atsushi/xgboost-predictor-java#9]
Hi,

do you have any plans to add a scala API which would nicely fit into the spark world of xgboost4j-spark?

**Comment by komiya-atsushi** [comment]
Hi,

Currently, I don't have any concrete plans yet.

(I want to add Scala API but I don't know well about Scala...)

**Comment by komiya-atsushi** [comment]
I just made [xgboost-predictor-spark](https://github.com/komiya-atsushi/xgboost-predictor-java/tree/master/xgboost-predictor-spark) that provides xgboost-predictor functions as Spark ML API.
If you have any interests in the module, please try to use it 😃
